import blockchain from './assets/blockchain.jpg'
import cyber from './assets/cyber.jpg'
import business from './assets/image2.jpg'
import dash from './assets/image1.jpg'
import full from './assets/full.jpg'
import forex from './assets/forex.png'
import shake from './assets/AI-Shake.png'
import project from './assets/project.jpg'


export const coursesData = [
    {
      id: 1,
      image: full,
      name: 'FullStack development with React & NodeJS',
      price: '130',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
        language: 'Language - English [Subtitle Added]',
        date: 'Posted on June 15, 2024'
      },
      phase1: {
        phaseName: 'React JS Basic Concept',
        phaseList: 'Introduction',
        phaseList1: 'JSX Introduction',
        phaseList2: 'Components',
        phaseList3: 'Conditional rendering ',
        phaseList4: 'Props Drilling',
      },
      phase2: {
        phaseName: 'Hooks Introduction',
        phaseList: 'useState Hooks',
        phaseList1: 'useEffect Hooks',
        phaseList2: 'useRef Hooks',
        phaseList3: 'useMemo Hooks',
        phaseList4: 'useContext Hook',
      },
      phase3: {
        phaseName: 'Introduction to React Redux',
        phaseList: 'Context API',
        phaseList1: 'React Events introduction',
        phaseList2: 'onclick capture events',
        phaseList3: 'onsubmit capture events',
        phaseList4: 'onscroll events',
      },
      phase4: {
        phaseName: 'Lifecycle of components',
        phaseList: 'Introduction to constructors',
        phaseList1: 'component DidMount',
        phaseList2: 'componentWillUnmount',
        phaseList3: 'componentDidUpdate',
        phaseList4: 'componentDidCatch',

      }
    },
    {
      id: 2,
      image: business,
      name: 'Python For Data Analysis',
      price: '110',
      standard: 'Beginners to Advanced',
      courseDetail: {
        description: 'Learn how to analyze data with Python using libraries like NumPy, Pandas, and Matplotlib. Master data cleaning, visualization, and manipulation for real-world applications.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Python Basics & Data Structures',
        phaseList: 'Installing Python & IDEs',
        phaseList1: 'Variables and Data Types',
        phaseList2: 'Conditional Statements',
        phaseList3: 'Loops and Iterations',
        phaseList4: 'Lists, Tuples, and Dictionaries',
      },
      phase2: {
        phaseName: 'Working with Data using Pandas',
        phaseList: 'Reading CSV/Excel Files',
        phaseList1: 'Data Cleaning and Preprocessing',
        phaseList2: 'Data Manipulation with Pandas',
        phaseList3: 'Merging and Grouping Data',
        phaseList4: 'Time Series Analysis',
      },
      phase3: {
        phaseName: 'Data Visualization',
        phaseList: 'Introduction to Matplotlib',
        phaseList1: 'Plotting Line Charts and Bar Graphs',
        phaseList2: 'Seaborn for Statistical Plots',
        phaseList3: 'Customizing Charts',
        phaseList4: 'Building Dashboards',
      },
      phase4: {
        phaseName: 'Basic Machine Learning',
        phaseList: 'Intro to Scikit-learn',
        phaseList1: 'Train/Test Split',
        phaseList2: 'Linear Regression',
        phaseList3: 'Classification Basics',
        phaseList4: 'Evaluating Model Performance',
      }
    },
    
    {
      id: 3,
      image: dash,
      name: 'Business Analysis ',
      price: '160',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Introduction to Business Analysis',
        phaseList: 'Role of a Business Analyst',
        phaseList1: 'Business Analysis Process',
        phaseList2: 'Requirements Gathering Techniques',
        phaseList3: 'Stakeholder Management',
        phaseList4: 'Business Case Development',
      },
      phase2: {
        phaseName: 'Modeling Techniques',
        phaseList: 'Use Case Diagrams',
        phaseList1: 'Data Flow Diagrams',
        phaseList2: 'Process Modeling (BPMN)',
        phaseList3: 'Gap Analysis',
        phaseList4: 'SWOT & PESTLE Analysis',
      },
      phase3: {
        phaseName: 'Solution Evaluation',
        phaseList: 'Defining KPIs',
        phaseList1: 'Cost-Benefit Analysis',
        phaseList2: 'Risk Management',
        phaseList3: 'Feasibility Study',
        phaseList4: 'Post-Implementation Review',
      },
      phase4: {
        phaseName: 'Agile & Tools',
        phaseList: 'Agile Business Analysis',
        phaseList1: 'Scrum Framework Overview',
        phaseList2: 'JIRA & Confluence Usage',
        phaseList3: 'Documentation Best Practices',
        phaseList4: 'BA Career Path & Certification',
      }
    },      
    {
      id: 4,
      image: forex,
      name: 'Ultimate Forex Trading Course',
      price: '90',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024'
      },
      phase1: {
        phaseName: 'Introduction to Forex',
        phaseList: 'What is Forex Trading?',
        phaseList1: 'Major Currency Pairs',
        phaseList2: 'Understanding Pips and Lots',
        phaseList3: 'Forex Market Sessions',
        phaseList4: 'Setting Up a Demo Account',
      },
      phase2: {
        phaseName: 'Technical Analysis',
        phaseList: 'Chart Types and Time Frames',
        phaseList1: 'Support and Resistance',
        phaseList2: 'Candlestick Patterns',
        phaseList3: 'Trend Lines and Channels',
        phaseList4: 'Indicators: RSI, MACD',
      },
      phase3: {
        phaseName: 'Fundamental Analysis',
        phaseList: 'Economic Indicators',
        phaseList1: 'Interest Rates & Inflation',
        phaseList2: 'News Trading Strategies',
        phaseList3: 'Central Bank Policies',
        phaseList4: 'Using Forex Calendars',
      },
      phase4: {
        phaseName: 'Risk Management & Strategy',
        phaseList: 'Leverage and Margin',
        phaseList1: 'Stop Loss & Take Profit',
        phaseList2: 'Position Sizing',
        phaseList3: 'Building a Trading Plan',
        phaseList4: 'Psychology of Trading',
      }
    },
    {
      id: 5,
      image: shake ,
      name: 'Introduction To Artificial Intelligence',
      price: '150',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'AI Fundamentals',
        phaseList: 'History of AI',
        phaseList1: 'Branches of AI',
        phaseList2: 'Applications of AI',
        phaseList3: 'Ethical Considerations',
        phaseList4: 'Future of AI',
      },
      phase2: {
        phaseName: 'Machine Learning Basics',
        phaseList: 'Types of Machine Learning',
        phaseList1: 'Supervised vs Unsupervised Learning',
        phaseList2: 'Classification vs Regression',
        phaseList3: 'Overfitting & Underfitting',
        phaseList4: 'Train-Test Split',
      },
      phase3: {
        phaseName: 'Working with AI Tools',
        phaseList: 'Introduction to Python for AI',
        phaseList1: 'Using Scikit-learn',
        phaseList2: 'Building a Basic Model',
        phaseList3: 'Evaluating Models',
        phaseList4: 'Hyperparameter Tuning',
      },
      phase4: {
        phaseName: 'Neural Networks & Deep Learning',
        phaseList: 'Basics of Neural Networks',
        phaseList1: 'Activation Functions',
        phaseList2: 'Forward & Back Propagation',
        phaseList3: 'Convolutional Neural Networks',
        phaseList4: 'AI Project Showcase',
      }
    },
    {
      id: 6,
      image: project,
      category: 'popular',
      name: 'Project Management Course',
      price: '125',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Project Management Basics',
        phaseList: 'What is Project Management?',
        phaseList1: 'The Role of a Project Manager',
        phaseList2: 'Project Life Cycle',
        phaseList3: 'Project Charter & Scope',
        phaseList4: 'Triple Constraint Theory',
      },
      phase2: {
        phaseName: 'Planning & Execution',
        phaseList: 'Work Breakdown Structure',
        phaseList1: 'Gantt Charts & Scheduling',
        phaseList2: 'Resource Allocation',
        phaseList3: 'Risk Management Planning',
        phaseList4: 'Communication Plans',
      },
      phase3: {
        phaseName: 'Monitoring & Controlling',
        phaseList: 'Key Performance Indicators',
        phaseList1: 'Earned Value Management',
        phaseList2: 'Change Management',
        phaseList3: 'Issue Resolution',
        phaseList4: 'Quality Control',
      },
      phase4: {
        phaseName: 'Agile & Certification',
        phaseList: 'Agile vs Waterfall',
        phaseList1: 'Scrum Roles & Ceremonies',
        phaseList2: 'PMI Certifications Overview',
        phaseList3: 'PMP vs PRINCE2 vs CSM',
        phaseList4: 'Project Closure & Lessons Learned',
      }
    },
    {
      id: 7,
      image: cyber,
      category: 'popular',
      name: 'ISC2 Cyber Security',
      price: '110',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Cyber Security Essentials',
        phaseList: 'CIA Triad Overview',
        phaseList1: 'Common Threats & Vulnerabilities',
        phaseList2: 'Malware Types',
        phaseList3: 'Password Security',
        phaseList4: 'Cybersecurity Frameworks',
      },
      phase2: {
        phaseName: 'Network Security',
        phaseList: 'Firewalls and IDS/IPS',
        phaseList1: 'VPNs and Tunneling Protocols',
        phaseList2: 'Network Topologies',
        phaseList3: 'Wireless Security',
        phaseList4: 'Network Segmentation',
      },
      phase3: {
        phaseName: 'Application and Data Security',
        phaseList: 'Secure Coding Practices',
        phaseList1: 'Database Security Basics',
        phaseList2: 'OWASP Top 10',
        phaseList3: 'Data Encryption Methods',
        phaseList4: 'Backup & Recovery',
      },
      phase4: {
        phaseName: 'Governance and Compliance',
        phaseList: 'Risk Assessment',
        phaseList1: 'Security Policies',
        phaseList2: 'Incident Response',
        phaseList3: 'ISO 27001 Overview',
        phaseList4: 'GDPR & HIPAA',
      }
    },      
    {
      id: 8,
      image: blockchain,
      category: 'popular',
      name: 'BlockChain and Cryptocurrency',
      price: '200',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Blockchain Basics',
        phaseList: 'What is Blockchain?',
        phaseList1: 'Distributed Ledger Technology',
        phaseList2: 'Consensus Mechanisms',
        phaseList3: 'Blocks and Hashing',
        phaseList4: 'Smart Contracts',
      },
      phase2: {
        phaseName: 'Cryptocurrency Fundamentals',
        phaseList: 'Bitcoin vs Altcoins',
        phaseList1: 'How Mining Works',
        phaseList2: 'Crypto Wallets',
        phaseList3: 'Exchanges & Trading',
        phaseList4: 'Tokenomics',
      },
      phase3: {
        phaseName: 'Blockchain Applications',
        phaseList: 'DeFi Overview',
        phaseList1: 'NFTs & Digital Ownership',
        phaseList2: 'Supply Chain Use Cases',
        phaseList3: 'Identity Management',
        phaseList4: 'Voting Systems',
      },
      phase4: {
        phaseName: 'Security and Regulation',
        phaseList: 'Blockchain Security Risks',
        phaseList1: '51% Attacks',
        phaseList2: 'Regulatory Environment',
        phaseList3: 'KYC & AML Compliance',
        phaseList4: 'Future of Blockchain',
      }
    },      
]